### ISSUE TITLE
Use unitValue from config.json file for each asset instead of hardcoded value

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldex-ui#19]
The `div` property https://github.com/Leasehold/ldex-ui/pull/18/files#diff-8d1dfa6a15e3dd0647fc1f2a673dcc2aR344 is hardcoded.
It's also hardcoded when calculating the balance here https://github.com/Leasehold/ldex-ui/pull/18/files#diff-8d1dfa6a15e3dd0647fc1f2a673dcc2aR333

This number depends on the asset so it should come from the `config.json` file; from the `unitValue` property.

**Comment by sacOO7** [comment]
Can you check one more comment on https://github.com/Leasehold/ldex-ui/pull/18/files#diff-8d1dfa6a15e3dd0647fc1f2a673dcc2aR333

**Comment by jondubois** [comment]
The amounts should be shown based on the unit value which is loaded from the config.json file or from the /status endpoint. When rounding the balance according to this unit value, we should round to 2 decimal places; the number of decimal places to round to can be hardcoded, it's just the units that cannot be hardcoded.

In the case of Lisk, 1 LSK = 100000000 Beddows (this is what `unitValue` means).
The blockchain API gives all values in the smallest unit possible (Beddows in the case of LSK) so we need to divide by `unitValue` for the `LSK` asset in order to know how many LSK the user has.

As an example, for Ethereum, 1 ETH = 10 ^ 18 Wei so the unit value would be 10 ^ 18 (different than LSK). Each asset can have different unit value.

How many decimal places to show on the UI doesn't depend on the asset; so it can be hardcoded to 2 decimal places.

**Comment by sacOO7** [comment]
In market.js, can exchangeFeeRate be inferred from config. file?
https://github.com/Leasehold/ldex-ui/blob/34d9a399369667b831636879ac3997745e59270b/lisk-dex-electron/src/Market.js#L33

**Comment by sacOO7** [comment]
Also, we get value for priceDecimalPrecision, can it also be used in hardcoded values?

**Comment by sacOO7** [comment]
@jondubois

**Comment by sacOO7** [comment]
Moving every repetition under common code.
