### ISSUE TITLE
Create an interface which can support any blockchain client (provided in config.json)

### ISSUE THREAD

**Issue by jondubois** [Capitalisk/ldex-ui#26]
The `ldex-ui` client needs to support any blockchain client (not just Lisk client logic). Right now the Lisk-specific client logic is spread in different parts of the code and need to be abstracted and hidden away inside a new `ChainClient` class.

For example `LiskChainClient` class would fully abstract away the functionality provided by the following dependencies:

- `@liskhq/lisk-cryptography`
- `@liskhq/lisk-passphrase`
- `@liskhq/lisk-transactions`

Users of the application should be able to specify different clients for different blockchain `assets` (this will also be useful for the upcoming Lisk v3). Each entry inside `config.json` in the `assets` object should contain the `blockchainClientLibPath` to use. 

The client for each supported asset should be be `require`d then instantiated inside `App.jsx`, then each client instance should be passed to the relevant React components (either as component attributes or via `context`).

Guidelines:

- Try to keep the interface of the `ChainClient/LiskChainClient` interface/class as simple as possible (simple methods, simple arguments, simple return values, ...). The interface should not need to be specified explicitly. `LiskChainClient` library can be used as the default client.
- Keep refactoring to a minimum (just to abstract away the blockchain-specific client functionality).

**Comment by sacOO7** [comment]
Okay, it will take some time for me to do the analysis. I will go through the requirements and check w.r.t. current implementation.

**Comment by jondubois** [comment]
Also, ideally, the client should expose some methods for communicating with the blockchain's API (e.g. HTTP API, but can also be WebSockets or other). So it should abstract away from specific blockchain API implementations.

**Comment by sacOO7** [comment]
I was going through the usages of 

```
@liskhq/lisk-cryptography
@liskhq/lisk-passphrase
@liskhq/lisk-transactions
```
- It seems they are not being used that heavily, just simple imports along with the use of static methods. I will update my analysis for the same here.
- Maybe common business logic is something we are looking to extract out.

**Comment by sacOO7** [comment]
```
@liskhq/lisk-cryptography
```

- Used in ```App.jsx``` and ```SignInModal.jsx```
- Used as ```cryptography.getAddressAndPublicKeyFromPassphrase(passphrase);```

```
@liskhq/lisk-passphrase
```
- Used in ```App.jsx``` and ```SignInModal.jsx```
- Imported ```Mnemonic```, used as ```Mnemonic.validateMnemonic(passphrase, Mnemonic.wordlists.english)```

```
@liskhq/lisk-transactions
```
- Used in ```PlaceOrder.jsx``` and ```UserOrder.jsx```
- Code is
```   
  const tx = transactions.transfer({
    amount: transactions.utils.convertLSKToBeddows('0.11').toString(),
    recipientId: dexAddress,
    data: `${targetChain},close,${orderId}`,
    passphrase,
  });
```

**Comment by sacOO7** [comment]
Above are the only code snippets where library imports are used.

**Comment by jondubois** [comment]
@sacOO7 Sounds good. We should wrap it inside a simple `LiskChainClient` class.
Based on this, it should expose at least:

1. A method to creating a signed transaction (to wrap around `transactions.transfer(...)` method). Maybe we can call it `prepareTransaction` for consistency with other related projects.
2. A method to check if a mnemonic passphrase is valid or not.
3. A method to allow converting a passphrase into a wallet address.

The third (3) method should be optional because some blockchains may not have a direct mapping from a passphrase to wallet address. In these cases, the user will need to provide both their address and passphrase when logging into the DEX UI. We will need to adjust the UI to allow this.

In addition to the 3 methods above, there should be additional methods for interacting with a blockchain such as submitting a prepared/signed transaction to the relevant blockchain and one for reading a list of transactions. Currently this is done directly via `axios` HTTP requests. For example https://github.com/Leasehold/ldex-ui/blob/3047c5e872abd762c8867a9ecdd34e1271bfdd55/lisk-dex-electron/src/App.jsx#L150 These are scattered throughout the source. We should wrap these HTTP calls inside new methods which abstract from HTTP. LDEX UI should also support WebSockets, for example.

We don't need to worry about the HTTP calls here https://github.com/Leasehold/ldex-ui/blob/master/lisk-dex-electron/src/API.js because those use the DEX API. We only need to abstract calls to blockchain nodes (asset API), not to DEX API.

**Comment by jondubois** [comment]
Adapters are now supported but unfortunately electron build step makes it difficult to import client libraries dynamically from a config so now they have to be required into the application logic. Currently 3 different blockchain clients are supported:

- Lisk v2
- Lisk v3
- LDPoS
